### PR TITLE
#3 Create service method for send "codenjoy" 

### PR DESCRIPTION
**Pull request by NikolayNN**
it is my solution for the task. I implement sending codenjoy request using Gamification API.
And add test for the method. Gamification service mocked by MockRestServiceServer.
please review my code.

### CODE REVIEW

**Comment by adaleorion** [comment]
thanks, i'm going to do today

**Comment by adaleorion** [comment]
for the future, please start your commit message with #1:  when 1 - number task

**Comment by NikolayNN** [comment]
merged solution for the task - #3 Create service method for send "codenjoy"
I sorry, i didn't use task number in the commits. I read your comment too late.

**Comment by adaleorion** [comment]
good work :+1:

**Review by adaleorion — APPROVED** [review]
well done

**Pull request merged**
